#Awesome Locally Generated Makefile

odir:
	-mkdir .objs

.objs/dumb_atexit.o: src/core/atexit.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/atexit.c		-o .objs/dumb_atexit.o
.objs/dumb_duhlen.o: src/core/duhlen.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/duhlen.c		-o .objs/dumb_duhlen.o
.objs/dumb_duhtag.o: src/core/duhtag.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/duhtag.c		-o .objs/dumb_duhtag.o
.objs/dumb_dumbfile.o: src/core/dumbfile.c src/core/dumb.h
	gcc -c src/core/dumbfile.c		-o .objs/dumb_dumbfile.o
.objs/dumb_loadduh.o: src/core/loadduh.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/loadduh.c		-o .objs/dumb_loadduh.o
.objs/dumb_makeduh.o: src/core/makeduh.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/makeduh.c		-o .objs/dumb_makeduh.o
.objs/dumb_rawsig.o: src/core/rawsig.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/rawsig.c		-o .objs/dumb_rawsig.o
.objs/dumb_readduh.o: src/core/readduh.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/readduh.c		-o .objs/dumb_readduh.o
.objs/dumb_register.o: src/core/register.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/register.c		-o .objs/dumb_register.o
.objs/dumb_rendduh.o: src/core/rendduh.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/rendduh.c		-o .objs/dumb_rendduh.o
.objs/dumb_rendsig.o: src/core/rendsig.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/rendsig.c		-o .objs/dumb_rendsig.o
.objs/dumb_unload.o: src/core/unload.c src/core/dumb.h src/core/internal/dumb.h
	gcc -c src/core/unload.c		-o .objs/dumb_unload.o
.objs/dumb_clickrem.o: src/helpers/clickrem.c src/helpers/dumb.h
	gcc -c src/helpers/clickrem.c		-o .objs/dumb_clickrem.o
.objs/dumb_memfile.o: src/helpers/memfile.c src/helpers/dumb.h
	gcc -c src/helpers/memfile.c		-o .objs/dumb_memfile.o
.objs/dumb_resample.o: src/helpers/resample.c src/helpers/dumb.h src/helpers/resample.inc src/helpers/resamp2.inc src/helpers/resamp3.inc
	gcc -c src/helpers/resample.c		-o .objs/dumb_resample.o
.objs/dumb_sampbuf.o: src/helpers/sampbuf.c src/helpers/dumb.h
	gcc -c src/helpers/sampbuf.c		-o .objs/dumb_sampbuf.o
.objs/dumb_silence.o: src/helpers/silence.c src/helpers/dumb.h
	gcc -c src/helpers/silence.c		-o .objs/dumb_silence.o
.objs/dumb_stdfile.o: src/helpers/stdfile.c src/helpers/dumb.h
	gcc -c src/helpers/stdfile.c		-o .objs/dumb_stdfile.o
.objs/dumb_itload2.o: src/it/itload2.c src/it/dumb.h
	gcc -c src/it/itload2.c		-o .objs/dumb_itload2.o
.objs/dumb_itload.o: src/it/itload.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/itload.c		-o .objs/dumb_itload.o
.objs/dumb_itmisc.o: src/it/itmisc.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/itmisc.c		-o .objs/dumb_itmisc.o
.objs/dumb_itorder.o: src/it/itorder.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/itorder.c		-o .objs/dumb_itorder.o
.objs/dumb_itread2.o: src/it/itread2.c src/it/dumb.h
	gcc -c src/it/itread2.c		-o .objs/dumb_itread2.o
.objs/dumb_itread.o: src/it/itread.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/itread.c		-o .objs/dumb_itread.o
.objs/dumb_itrender.o: src/it/itrender.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/itrender.c		-o .objs/dumb_itrender.o
.objs/dumb_itunload.o: src/it/itunload.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/itunload.c		-o .objs/dumb_itunload.o
.objs/dumb_loadmod2.o: src/it/loadmod2.c src/it/dumb.h
	gcc -c src/it/loadmod2.c		-o .objs/dumb_loadmod2.o
.objs/dumb_loadmod.o: src/it/loadmod.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/loadmod.c		-o .objs/dumb_loadmod.o
.objs/dumb_loads3m2.o: src/it/loads3m2.c src/it/dumb.h
	gcc -c src/it/loads3m2.c		-o .objs/dumb_loads3m2.o
.objs/dumb_loads3m.o: src/it/loads3m.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/loads3m.c		-o .objs/dumb_loads3m.o
.objs/dumb_loadxm2.o: src/it/loadxm2.c src/it/dumb.h
	gcc -c src/it/loadxm2.c		-o .objs/dumb_loadxm2.o
.objs/dumb_loadxm.o: src/it/loadxm.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/loadxm.c		-o .objs/dumb_loadxm.o
.objs/dumb_readmod2.o: src/it/readmod2.c src/it/dumb.h
	gcc -c src/it/readmod2.c		-o .objs/dumb_readmod2.o
.objs/dumb_readmod.o: src/it/readmod.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/readmod.c		-o .objs/dumb_readmod.o
.objs/dumb_reads3m2.o: src/it/reads3m2.c src/it/dumb.h
	gcc -c src/it/reads3m2.c		-o .objs/dumb_reads3m2.o
.objs/dumb_reads3m.o: src/it/reads3m.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/reads3m.c		-o .objs/dumb_reads3m.o
.objs/dumb_readxm2.o: src/it/readxm2.c src/it/dumb.h
	gcc -c src/it/readxm2.c		-o .objs/dumb_readxm2.o
.objs/dumb_readxm.o: src/it/readxm.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/readxm.c		-o .objs/dumb_readxm.o
.objs/dumb_xmeffect.o: src/it/xmeffect.c src/it/dumb.h src/it/internal/it.h
	gcc -c src/it/xmeffect.c		-o .objs/dumb_xmeffect.o

$(DEST)/libdumb.a: odir .objs/dumb_atexit.o .objs/dumb_duhlen.o .objs/dumb_duhtag.o .objs/dumb_dumbfile.o .objs/dumb_loadduh.o .objs/dumb_makeduh.o .objs/dumb_rawsig.o .objs/dumb_readduh.o .objs/dumb_register.o .objs/dumb_rendduh.o .objs/dumb_rendsig.o .objs/dumb_unload.o .objs/dumb_clickrem.o .objs/dumb_memfile.o .objs/dumb_resample.o .objs/dumb_sampbuf.o .objs/dumb_silence.o .objs/dumb_stdfile.o .objs/dumb_itload2.o .objs/dumb_itload.o .objs/dumb_itmisc.o .objs/dumb_itorder.o .objs/dumb_itread2.o .objs/dumb_itread.o .objs/dumb_itrender.o .objs/dumb_itunload.o .objs/dumb_loadmod2.o .objs/dumb_loadmod.o .objs/dumb_loads3m2.o .objs/dumb_loads3m.o .objs/dumb_loadxm2.o .objs/dumb_loadxm.o .objs/dumb_readmod2.o .objs/dumb_readmod.o .objs/dumb_reads3m2.o .objs/dumb_reads3m.o .objs/dumb_readxm2.o .objs/dumb_readxm.o .objs/dumb_xmeffect.o 
	ar r $(DEST)/libdumb.a .objs/*.o

static: $(DEST)/libdumb.a

clean:
	-rm .objs/*
