../$(DEST)/analysis.o: analysis.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/registry.h lib/scales.h
	g++ -c analysis.c		-o $(DEST)/analysis.o $(FLAGS)
../$(DEST)/barkmel.o: barkmel.c lib/scales.h lib/os.h lib/config.h lib/misc.h
	g++ -c barkmel.c		-o $(DEST)/barkmel.o $(FLAGS)
../$(DEST)/bitrate.o: bitrate.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h
	g++ -c bitrate.c		-o $(DEST)/bitrate.o $(FLAGS)
../$(DEST)/block.o: block.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/window.h lib/lpc.h lib/registry.h
	g++ -c block.c		-o $(DEST)/block.o $(FLAGS)
../$(DEST)/codebook.o: codebook.c lib/codebook.h lib/scales.h lib/os.h lib/config.h lib/misc.h
	g++ -c codebook.c		-o $(DEST)/codebook.o $(FLAGS)
../$(DEST)/envelope.o: envelope.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/scales.h
	g++ -c envelope.c		-o $(DEST)/envelope.o $(FLAGS)
../$(DEST)/floor0.o: floor0.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/registry.h lib/lpc.h lib/lsp.h lib/scales.h
	g++ -c floor0.c		-o $(DEST)/floor0.o $(FLAGS)
../$(DEST)/floor1.o: floor1.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/registry.h lib/scales.h
	g++ -c floor1.c		-o $(DEST)/floor1.o $(FLAGS)
../$(DEST)/info.o: info.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/registry.h lib/window.h
	g++ -c info.c		-o $(DEST)/info.o $(FLAGS)
../$(DEST)/lookup.o: lookup.c lib/lookup.h lib/lookup_data.h lib/os.h lib/config.h lib/misc.h
	g++ -c lookup.c		-o $(DEST)/lookup.o $(FLAGS)
../$(DEST)/lpc.o: lpc.c lib/os.h lib/config.h lib/misc.h lib/smallft.h lib/lpc.h lib/scales.h
	g++ -c lpc.c		-o $(DEST)/lpc.o $(FLAGS)
../$(DEST)/lsp.o: lsp.c lib/lsp.h lib/os.h lib/config.h lib/misc.h lib/lookup.h lib/scales.h lib/lookup.c lib/lookup_data.h
	g++ -c lsp.c		-o $(DEST)/lsp.o $(FLAGS)
../$(DEST)/mapping0.o: mapping0.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/window.h lib/registry.h lib/lpc.h lib/lsp.h lib/scales.h
	g++ -c mapping0.c		-o $(DEST)/mapping0.o $(FLAGS)
../$(DEST)/mdct.o: mdct.c lib/mdct.h lib/os.h lib/config.h lib/misc.h
	g++ -c mdct.c		-o $(DEST)/mdct.o $(FLAGS)
../$(DEST)/psy.o: psy.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/masking.h lib/lpc.h lib/scales.h
	g++ -c psy.c		-o $(DEST)/psy.o $(FLAGS)
../$(DEST)/registry.o: registry.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/registry.h
	g++ -c registry.c		-o $(DEST)/registry.o $(FLAGS)
../$(DEST)/res0.o: res0.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/registry.h
	g++ -c res0.c		-o $(DEST)/res0.o $(FLAGS)
../$(DEST)/sharedbook.o: sharedbook.c lib/os.h lib/config.h lib/misc.h lib/codebook.h lib/scales.h
	g++ -c sharedbook.c		-o $(DEST)/sharedbook.o $(FLAGS)
../$(DEST)/smallft.o: smallft.c lib/smallft.h lib/os.h lib/config.h lib/misc.h
	g++ -c smallft.c		-o $(DEST)/smallft.o $(FLAGS)
../$(DEST)/synthesis.o: synthesis.c lib/codec_internal.h lib/envelope.h lib/mdct.h lib/codebook.h lib/psy.h lib/smallft.h lib/backends.h lib/bitrate.h lib/os.h lib/config.h lib/misc.h lib/highlevel.h lib/registry.h
	g++ -c synthesis.c		-o $(DEST)/synthesis.o $(FLAGS)
../$(DEST)/tone.o: tone.c
	g++ -c tone.c		-o $(DEST)/tone.o $(FLAGS)
../$(DEST)/vorbisfile.o: vorbisfile.c lib/os.h lib/config.h lib/misc.h
	g++ -c vorbisfile.c		-o $(DEST)/vorbisfile.o $(FLAGS)
../$(DEST)/window.o: window.c lib/os.h lib/config.h lib/misc.h
	g++ -c window.c		-o $(DEST)/window.o $(FLAGS)

all: ../$(DEST)/lib/*.o 

clean:















